import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
function setup(consent=true,paid=false){let now=0,shown=0,banners=0,initialized=0;const events={},handlers={};const plugin={addListener:async(k,cb)=>{events[k]=cb;},requestConsentInfo:async()=>({canRequestAds:consent,isConsentFormAvailable:false,status:'NOT_REQUIRED'}),initialize:async()=>{initialized++;},showBanner:async()=>{banners++;},hideBanner:async()=>{},prepareInterstitial:async()=>{},showInterstitial:async()=>{shown++;},showPrivacyOptionsForm:async()=>{}};
const window={MIVA_CONFIG:{ads:{enabled:true,test:true,bannerId:'test',interstitialId:'test',cooldownSeconds:180,everySaves:3,minUseSeconds:6}},Capacitor:{getPlatform:()=> 'android',registerPlugin:()=>plugin},alert(){}};const document={visibilityState:'visible',documentElement:{style:{setProperty(){}}},addEventListener:(k,f)=>{handlers[k]=f;}};
const ctx=vm.createContext({window,document,Date:{now:()=>now},console});vm.runInContext(fs.readFileSync('www/ads.js','utf8'),ctx);return {api:window.MivaAds,events,document,advance:n=>now=n,get shown(){return shown},get banners(){return banners},get initialized(){return initialized},paid};}
test('six seconds idle never shows an ad; only eligible natural break does',async()=>{const a=setup();await a.api.init(()=>false);await Promise.resolve();a.advance(6000);assert.equal(a.shown,0);let moved=0;for(let i=0;i<3;i++)a.api.atBreak(()=>moved++);assert.equal(a.shown,0);assert.equal(moved,3);a.advance(180000);a.api.atBreak(()=>moved++);assert.equal(a.shown,1);assert.equal(moved,3);a.events.interstitialAdDismissed();assert.equal(moved,4);a.api.atBreak(()=>moved++);assert.equal(a.shown,1);});
test('no consent, Pro and background prevent ads',async()=>{const a=setup(false);await a.api.init(()=>false);assert.equal(a.initialized,0);const b=setup();await b.api.init(()=>true);assert.equal(b.banners,0);const c=setup();await c.api.init(()=>false);c.advance(200000);c.document.visibilityState='hidden';for(let i=0;i<5;i++)c.api.atBreak(()=>{});assert.equal(c.shown,0);});

test('demo initialization does not depend on publisher UMP configuration',async()=>{const a=setup(false); // Use a fresh mocked demo app.
 let initialized=0;const handlers={};const plugin={addListener:async(k,f)=>{handlers[k]=f;},requestConsentInfo:async()=>{throw Error('publisher config');},initialize:async()=>{initialized++;},showBanner:async()=>{},prepareInterstitial:async()=>{}};
 const window={MIVA_CONFIG:{ads:{enabled:true,test:true,bannerId:'ca-app-pub-3940256099942544/6300978111',interstitialId:'ca-app-pub-3940256099942544/1033173712'}},Capacitor:{getPlatform:()=> 'android',registerPlugin:()=>plugin}};const ctx=vm.createContext({window,document:{visibilityState:'visible',documentElement:{style:{setProperty(){}}},addEventListener(){}},console,Date});vm.runInContext(fs.readFileSync('www/ads.js','utf8'),ctx);await window.MivaAds.init(()=>false);assert.equal(initialized,1);assert.equal(window.MivaAds.status().ready,true);});
test('production errors are visible and do not bypass consent',async()=>{const a=setup(false);await a.api.init(()=>false);assert.match(a.api.status().stage,/consentimiento/);assert.equal(a.api.status().initialized,false);});
