import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync('src/billing.js','utf8').replace(/^import .*?;\n/,'');
const info=(active=true,verification='VERIFIED',expirationDate='2099-01-01T00:00:00Z')=>({entitlements:{verification,active:active?{pro:{isActive:true,verification,expirationDate}}:{}},managementURL:'https://play.google.com/store/account/subscriptions'});
function setup({enabled=true,purchaseError=null,initial=info(false)}={}){let current=initial,listener,purchases=0,restores=0;const events={};const monthly={identifier:'$rc_monthly',presentedOfferingContext:{offeringIdentifier:'default'},product:{identifier:'miva_pro_monthly:monthly',priceString:'ARS 2.000,00',subscriptionOptions:[{id:'monthly',isBasePlan:true,isPrepaid:false,billingPeriod:{iso8601:'P1M'},fullPricePhase:{price:{formatted:'ARS 2.000,00'}}}]}};
const Purchases={configure:async()=>{},addCustomerInfoUpdateListener:async cb=>{listener=cb;return 'id';},getCustomerInfo:async()=>({customerInfo:current}),getOfferings:async()=>({all:{default:{availablePackages:[monthly]}}}),purchaseSubscriptionOption:async({subscriptionOption})=>{assert.equal(subscriptionOption.id,'monthly');purchases++;if(purchaseError)throw purchaseError;current=info();return {customerInfo:current};},restorePurchases:async()=>{restores++;current=info();return {customerInfo:current};}};
const window={MIVA_CONFIG:{billing:{enabled,apiKey:'goog_test',entitlementId:'pro',offeringId:'default',productId:'miva_pro_monthly',basePlanId:'monthly'}},Capacitor:{getPlatform:()=> 'android'},open(){}};const ctx=vm.createContext({window,document:{addEventListener:(k,f)=>events[k]=f},Purchases,Date});vm.runInContext(source,ctx);return {api:window.MivaBilling,get purchases(){return purchases},get restores(){return restores},update:v=>{current=v;listener(v);},monthly};}
test('monthly purchase uses store price and SDK entitlement',async()=>{const a=setup();await a.api.init();assert.equal(a.api.status().price,'ARS 2.000,00');assert.equal(a.api.hasPro(),false);await a.api.buy();assert.equal(a.purchases,1);assert.equal(a.api.hasPro(),true);await a.api.buy();assert.equal(a.purchases,1);});
test('cancellation and pending payment do not unlock Pro',async()=>{for(const code of ['1','20']){const a=setup({purchaseError:{code}});await a.api.init();await a.api.buy();assert.equal(a.api.hasPro(),false);assert.match(a.api.status().message,code==='1'?/cancelada/:/pendiente/);assert.equal(a.api.status().busy,false);}});
test('restore and expiration updates grant and revoke access',async()=>{const a=setup();await a.api.init();await a.api.restore();assert.equal(a.restores,1);assert.equal(a.api.hasPro(),true);a.update(info(true,'VERIFIED','2020-01-01T00:00:00Z'));assert.equal(a.api.hasPro(),false);a.update(info(false));assert.equal(a.api.hasPro(),false);});
test('failed verification and annual products never enable monthly purchases',async()=>{const a=setup({initial:info(true,'FAILED')});await a.api.init();assert.equal(a.api.hasPro(),false);a.monthly.product.subscriptionOptions[0].billingPeriod.iso8601='P1Y';await a.api.refresh();assert.equal(a.api.status().ready,false);});
test('unconfigured billing is unavailable and never calls purchase',async()=>{const a=setup({enabled:false});await a.api.init();await a.api.buy();assert.equal(a.purchases,0);assert.equal(a.api.hasPro(),false);});
